

spring:
  datasource:
#    schema: classpath:schema.sql
#    data: classpath:data.sql
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql:///mybatisplus?useSSL=false&CharacterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT

    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///mybatisplus?useSSL=false&CharacterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver



#logging:
#  level:
#    cn:
#      lacknb:
#        mapper: debug

# 配置MyBatisPlus 日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1  # 对于已经删除的的值为1
      logic-not-delete-value: 0  # 没删除的 值为0

